-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_brands
(
    brand_id uuid NOT NULL,
    brand_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    brand_category character varying(100) COLLATE pg_catalog."default",
    brand_category_code character varying(50) COLLATE pg_catalog."default",
    brand_barcode character varying(50) COLLATE pg_catalog."default",
    is_top_brand boolean DEFAULT false,
    CONSTRAINT dim_brands_pkey PRIMARY KEY (brand_id)
);

CREATE TABLE IF NOT EXISTS public.dim_users
(
    user_id uuid NOT NULL,
    user_state character varying(2) COLLATE pg_catalog."default",
    account_created_date timestamp without time zone NOT NULL,
    last_login_date timestamp without time zone,
    user_role character varying(20) COLLATE pg_catalog."default" DEFAULT 'consumer'::character varying,
    is_active boolean DEFAULT true,
    CONSTRAINT dim_users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.fact_receipt_items
(
    receipt_item_id uuid NOT NULL,
    item_receipt_id uuid,
    item_brand_id uuid,
    item_barcode character varying(50) COLLATE pg_catalog."default",
    item_quantity integer DEFAULT 1,
    item_price numeric(10, 2) DEFAULT 0.00,
    CONSTRAINT fact_receipt_items_pkey PRIMARY KEY (receipt_item_id)
);

CREATE TABLE IF NOT EXISTS public.fact_receipts
(
    receipt_id uuid NOT NULL,
    receipt_user_id uuid,
    purchase_timestamp timestamp without time zone NOT NULL,
    scanned_date timestamp without time zone NOT NULL,
    processing_finished_date timestamp without time zone,
    receipt_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    total_amount_spent numeric(10, 2) DEFAULT 0.00,
    items_purchased_count integer DEFAULT 0,
    reward_points_earned integer DEFAULT 0,
    extra_bonus_points integer DEFAULT 0,
    points_awarded_timestamp timestamp without time zone,
    CONSTRAINT fact_receipts_pkey PRIMARY KEY (receipt_id)
);

ALTER TABLE IF EXISTS public.fact_receipt_items
    ADD CONSTRAINT fact_receipt_items_item_brand_id_fkey FOREIGN KEY (item_brand_id)
    REFERENCES public.dim_brands (brand_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.fact_receipt_items
    ADD CONSTRAINT fact_receipt_items_item_receipt_id_fkey FOREIGN KEY (item_receipt_id)
    REFERENCES public.fact_receipts (receipt_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.fact_receipts
    ADD CONSTRAINT fact_receipts_receipt_user_id_fkey FOREIGN KEY (receipt_user_id)
    REFERENCES public.dim_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
